[project]
name = "snipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click",
]

[project.scripts]
snipe = "cli.commands:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["cli*", "osint*"]
